import Header from "@/components/Header";
import "./globals.css";
import NextUIProvider from "./Providers";
import ReduxProvider from "@/redux/reduxProvider";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <NextUIProvider>
            <Header />
            {children}
            <Toaster
              position="top-right"
              gutter={12}
              containerStyle={{ margin: "8px" }}
              toastOptions={{
                success: {
                  duration: 2500,
                },
                error: {
                  duration: 4000,
                },
                style: {
                  fontSize: "16px",
                  maxWidth: "500px",
                  padding: "16px 24px",
                },
              }}
            />
          </NextUIProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
