"use client";
import Header from "@/components/Header";
import "./globals.css";
import NextUIProvider from "./Providers";
import ReduxProvider from "@/redux/reduxProvider";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import { useRouter } from "next/navigation";
import AdminLayout from "./(admin)/layout";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  if (router.pathname?.startsWith("/admin")) {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  } else {
    return (
      <html lang="en">
        <body>
          <ReduxProvider>
            <NextUIProvider>
              <Header />
              {children}
              <Footer />
              <Toaster
                position="top-right"
                gutter={12}
                containerStyle={{ margin: "8px" }}
                toastOptions={{
                  success: {
                    duration: 2500,
                  },
                  error: {
                    duration: 4000,
                  },
                  style: {
                    fontSize: "16px",
                    maxWidth: "500px",
                    padding: "16px 24px",
                  },
                }}
              />
            </NextUIProvider>
          </ReduxProvider>
        </body>
      </html>
    );
  }
}
