import "./globals.css";
import NextUIProviders from "./Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextUIProviders>{children}</NextUIProviders>
      </body>
    </html>
  );
}
